# Generated by Django 4.1.7 on 2023-02-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Marka Adı')),
                ('description', models.TextField(verbose_name='Marka Açıklaması')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='IHA.brand')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('slug', models.SlugField(default='', max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='İHA Adı')),
                ('model_number', models.CharField(max_length=100, verbose_name='İHA Modeli')),
                ('description', models.TextField(verbose_name='İHA Açıklaması')),
                ('weight', models.FloatField(verbose_name='İHA Ağırlığı')),
                ('image', models.ImageField(upload_to='iha_images', verbose_name='İHA Resmi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IHA.brand', verbose_name='Marka')),
                ('category', models.ManyToManyField(to='IHA.category', verbose_name='Kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
