# Generated by Django 4.1.7 on 2023-02-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IHA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iha',
            options={'verbose_name': 'Iha', 'verbose_name_plural': 'Insansiz Hava Araçları'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='parent_category',
        ),
    ]
