# Generated by Django 4.1.7 on 2023-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHA', '0002_alter_iha_options_remove_brand_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='iha_images', verbose_name='İHA Resmi'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='model_number',
            field=models.CharField(max_length=100, verbose_name='İHA Model Numarası'),
        ),
    ]
